Added "defaultMemoryMbytes" to actor.json
apifytech/actor-specs pull request #55
Opened 2024-12-05 22:07 UTC by jancurn

2024-12-06 08:15 UTC, fnesveda requested changes

2024-12-06 08:15 UTC, fnesveda commented on pages/ACTOR_FILE.md
> +  "defaultMemoryMbytes": "${maxCrawlPages} * 256 + 128",
Are we sure we want to have it this customizable? Right now the memory has to be a power of 2, which would be hard to enforce with a custom expression. We could relax the "power of 2" requirement, but I'm a bit worried about the implications on job allocation to workers if we allow completely custom memory.

Also it might be more readable to put `defaultMemoryMbytes` between `minMemoryMbytes` and `maxMemoryMbytes`, to make it a bit more clear that the calculated value is clamped from both sides, and have one comment for all three together.

2024-12-06 08:55 UTC, jancurn commented on pages/ACTOR_FILE.md
> +  "defaultMemoryMbytes": "${maxCrawlPages} * 256 + 128",
> Right now the memory has to be a power of 2

2024-12-06 08:57 UTC, jancurn commented on pages/ACTOR_FILE.md
> +  "defaultMemoryMbytes": "${maxCrawlPages} * 256 + 128",
> Right now the memory has to be a power of 2,

We could say we always ceil it to the next higher value available by the platform. This should apply to all three parameters.

> Are we sure we want to have it this customizable?

I think it's better to use an expression rather than some A and B linear coefficients.

2024-12-06 09:19 UTC, metalwarrior665 reviewed
I like this. This would probably remove the need to have charge the actor-start per GB or maybe charge it at all.

2024-12-06 14:30 UTC, jancurn commented
> I like this. ~This would probably remove the need to have charge the actor-start per GB or maybe charge it at all.~ No, this is just a default, they could override it so we would still have to charge per GB for the wrong configurers

In theory in the future we might disable ability to select custom memory, or per developer setting. This opens the path.

2024-12-06 14:32 UTC, jancurn commented
BTW perhaps this would be cleaner:

```
memory: {
  minMbytes: 128,
  maxMbytes: 4096,
  defaultMbytes: "${maxCrawlPages} * 256 + 128"
  // default: 1024 - this also works
}
```

What do you think guys?

2024-12-06 14:42 UTC, fnesveda commented
How about this?
- move `mbytes` suffix one higher
	- it's cleaner, but if there would be some other memory config which isn't directly related to the `mbytes` of memory available, it can't go into the object
- prefix the variables with `input.` to make it clear that they're referring to input values, not other values from `actor.json`
```js
memoryMbytes: {
    min: 128,
    default: "${input.maxCrawlPages} * 256 + 128"
    max: 4096,
}
```

2024-12-06 14:44 UTC, jancurn commented
IMO it's better to keep just `memory`, to have flexibility to add more stuff in the future. Also the convention is that variable names must end with the unit, not parent objects. So:

```
memory: {
    minMbytes: 128,
    defaultMbytes: "${input.maxCrawlPages} * 256 + 128"
    maxMbytes: 4096,
}
```

2024-12-06 14:52 UTC, jancurn commented
Or maybe we could make it even more generic and future proof:

```
runtime: {
    memoryMinMbytes: 128,
    memoryDefaultMbytes: "${input.maxCrawlPages} * 256 + 128"
    memoryMaxMbytes: 4096,
}

```

2025-02-25 14:49 UTC, metalwarrior665 commented
We recently got back to this with @fnesveda, let's get this moving? What do you think @mhamas @zpelechova ?

2025-02-25 15:39 UTC, zpelechova commented
I heard it ended up with @filipc77 . But I agree, please please let do this!

2025-02-26 06:17 UTC, jancurn commented
Yes, let's finish this specs. To keep things simple, I'd just add a new field `defaultMemoryMbytes` instead of that object, and added support for the simple arithmetic expressions (also for `minMemoryMbytes` and `maxMemoryMbytes` for consistency). 

@fnesveda @metalwarrior665 @mtrunkat what do you think guys?

2025-02-27 08:51 UTC, mtrunkat commented
Wouldn't be better to have `defaultRunOptions` object there? With `memoryMbytes, buildTag, timeoutSecs`? To be consistent with the structure, API, etc.? And to support it fully.

2025-02-28 15:48 UTC, metalwarrior665 commented
I did brainstorm how this could be used for various Actors and input types. There a few contentious points we need resolved. Here is a list going from most important to more weird. I'm ok if we only support point 1 and 2.

1. `integer` - E.g. `maxResults`. Most important and useful
    a) Would it support nested fields? E.g. `input.customGeolocation.radiusKm`
    b) IMPORTANT: What about optional fields? `maxResults` is often left empty as unlimited, in that case we want high memory setting. If we want to keep just using numbers, we would have to turn it to `0` but even that would require some hacky math.
2. `array.length` - E.g. `searchTerms.length`. This is often used in combination with `maxResultsPerSearch`.
     a) What if it is not an array and it crashes on property check?
4. `boolean` - E.g. `onlySearchPageData`. This could mean a different run mode that gives only a few results.
     a) We could convert to 0 and 1
5. `string` + `enum` - E.g. `minimumStarRating`, can significantly restrict results.
     a) We could assign numeric values 0, 1, 2. But it would break in reorder and feels really hacky. Or could be selected directly as property, e.g. minimumStarRating['fiveStars']
6. `string` + `regex` - E.g. type of URL, detail can give only 1 result
     a) This is probably too much

2025-03-08 06:51 UTC, jancurn commented
+1 to `defaultRunOptions`. In version 1, we can keep it simple and support just integers, and consider everything else 0.

2025-03-08 07:01 UTC, jancurn commented
On a second though about `defaultRunOptions`, `buildTag` is already in top level, so it would be confusing to move it to `defaultRunOptions` or duplicate. So I'd keep it simple and keep all these properties top-level.

In version 1, we can keep it simple and support just integers, and consider everything else 0.

2025-03-08 18:59 UTC, mtrunkat commented
@jancurn  Isn't it something different -
- `buildTag` says under what tag the code is going to be build after you do `apify push`, i.e., the `buildTag` of the version you are modifying
- where `defaultRunOptions.buildTag` is the tag that is used by default when you run the Actor?

2025-03-08 19:25 UTC, jancurn commented
Yes it is, but having two `buildTags` in actor.json will be confusing. In which situation those two would ever be different?

2025-03-08 19:31 UTC, mtrunkat commented
Ym it's confusing. But I can imagine my workflow to be

```
defaultRunOptions.buildTag="LATEST"
buildTag="BETA"
```

... once we allow manual changes to the tagging in UI, i.e., pushing it as a testing version and then overriding it after testing to the latest (=release),

2025-03-08 19:32 UTC, mtrunkat commented
In fact, I think that correct naming is

```
defaultRunOptions.build // Only build as this allows to choose version, tag, ID, or perhaps later also 2.*
buildTag
```

2025-03-09 05:52 UTC, jancurn commented
The thing is, build IDs are not part of the specification, and as they are dynamic you shouldn't check them into source control anyway. So I'd skip this for now

2025-03-10 08:26 UTC, fnesveda approved these changes

2025-03-10 16:57 UTC, metalwarrior665 commented
> In version 1, we can keep it simple and support just integers, and consider everything else 0.

We might have to rethink that we now use empty as default value for "maxResults" (means unlimited). I'm not sure what math expression we would have to use to make this work? E.g. we would want 
- 1 maxResults => 1 GB
- 100 maxResults => 4 GB
- `undefined` maxResults => 8 GB (max)

JS already returns `Infinity` from divide by zero so we could hack that...

2025-03-10 21:14 UTC, jancurn commented
Hmm, I see, let's keep such behavior undefined for now, we can solve this later.

2025-03-10 21:14 UTC, jancurn commented
Let's merge this, @metalwarrior665 @mtrunkat fine with you?

2025-03-11 07:33 UTC, zpelechova commented
Getting back to this, does it solve the user (aka my) problem? 
1. If a user comes, can they still choose the memory?
2. If they choose (or we lead them to choose) the memory too low, can we programmatically change it from within the code?
3. would both these options work: `defaultMbytes: "${maxCrawlPages} * 256 + 128"` and `default: 1024 - this also works` and if so
4. where do the `maxCrawlPages` come from? Is it one number from the input schema which I as a dev choose, is it the `max paid items` variable from PPR runs?
5. and if from input schema,  what if I have different limits there, aka places + reviews + images on Google maps or videos + shorts + streams on youtube

2025-03-11 08:43 UTC, metalwarrior665 approved these changes

2025-03-11 08:46 UTC, metalwarrior665 commented
@jancurn Yes, we can merge. But we will have to resolve the `undefined` problem or it is mostly unusable for us. We have 3 options:

1. We will always use a number, so something like `prefill: 200, default: 999999`. It looks uglier than an empty value, most people don't like this.
2. We update this feature so that `undefined` means Infinity or allow some more expressive logic
3. We give up and don't use this feature on most Actors.

2025-03-11 09:14 UTC, metalwarrior665 commented
@zpelechova 
1. Yes, this would be a default memory. That is now hardcoded in Actor settings, this would make it dynamic on the input. Forbidding user to change memory is a different independent feature that we can discuss later.
2. There would still be min/max memory like now. And we could implement the forbidding. In the code, we can resurrect but I think the reason for this feature is that we don't have to.
3. I'm not sure what you mean by `default: 1024 - this also works`. You mean that we would fallback to fixed value if e.g. there is no `maxCrawlPages`?
4. That's input field. But good comment that we need to handle PPR and PPE max values too. So we should probably allow `${input.maxCrawlPages}` and ${options.maxTotalChargeUsd} and ${options.maxChargedResults} cc @jancurn @fnesveda 
5. You would need to have more variables in the equation. E.g. `"${input.maxPlacesPerSearch} * 256 + ${input.maxReviews} * 5 + 128"`

2025-03-11 09:49 UTC, metalwarrior665 requested changes

2025-03-11 09:49 UTC, metalwarrior665 commented on pages/ACTOR_FILE.md
> +  "defaultMemoryMbytes": "${maxCrawlPages} * 256 + 128",
Let's make this `${input.maxCrawlPages}` so we don't have namespace clashes in the future

2025-03-11 10:23 UTC, zpelechova commented
So just to be sure, what are we trying to achieve by this?
We are not making the memory flexible, like for example with the concurency of the Actor, so it doesn grow when needed, we are just making i a slightly smarter default?
Will it show to the user somehow? 

And going into niche cases here, but what if someone uses 9999999 for input.maxCrawlPages but 5 for options.maxChargedResults? It will not happen often so I am ok with consiously ignoring it, just pointing that out.

2025-03-11 10:38 UTC, metalwarrior665 commented
@zpelechova 

1. We are trying to achieve what we have discussed for a long time. To make sure the memory is set to the ideal amount based on the Actor input - smaller amount of results = smaller memory, larger results = higher memory. And this is a way to do it right at the input, without need for any run resurrects or similar hacks.
2. Yes, it is smarter default. Flexible memory is not possible without restarting the run container, it would have to use resurrect in the code. We can do that even now but it is an ugly solution with problems - user might not have more memory available anymore, we are changing memory of their account under their hands, there it some time this reboot takes, etc. So I would go this way only as last resort
3. It will be shown as the greyed default in the memory like it is now. So if they save the input, the greyed value will change.
4. We should have access to both ${input.maxCrawlPages} and ${options.maxChargedResults} in the math expression so we can work with that. I'm not good at math so I don't know if there is a simple math expression do to "minimum of two" but we could introduce something like this in next version `"defaultMemoryMbytes": "Math.min(${input.maxCrawlPages}, options.maxChargedResults) * 256 + 128"`.

2025-03-11 11:30 UTC, zpelechova commented
Sounds good, thanks for the explanation, @metalwarrior665!

2025-03-18 15:41 UTC, mtrunkat approved these changes

2025-07-01 14:49 UTC, jancurn commented
Thanks @metalwarrior665 I've updated the specs. IMO we can merge this and try it

2025-07-01 14:53 UTC, jancurn commented
@gippy @mtrunkat @fnesveda final thoughts?

2025-07-02 11:30 UTC, metalwarrior665 approved these changes
Can we also add reference to ${options.maxTotalChargeUsd}?

2025-07-02 12:52 UTC, fnesveda requested changes
Just a few suggestions

2025-07-03 09:43 UTC, jancurn commented
@metalwarrior665 added example

2025-07-03 09:57 UTC, fnesveda requested changes
One more note about the namespaces

2025-07-03 09:57 UTC, fnesveda commented on pages/ACTOR_FILE.md
> +  // or Actor run (e.g. `{{actorRun.options.maxTotalChargeUsd}}`) similar to Output schema. It can also use basic arithmetic expressions.
I'm not really a fan of mixing the Actor and Actor run concepts and the different nesting levels (`actorInput` and `actorRun.options`) in the namespaces. It would be cleaner if it would be unified. One of these:
- `actorRun.input.variable` and `actorRun.options.maxTotalChargeUsd`
- `actor.input.variable` and `actor.options.maxTotalChargeUsd`
- `actorInput.variable` and `actorOptions.maxTotalChargeUsd`

2025-08-04 11:49 UTC, gippy requested changes

2025-08-05 15:07 UTC, tobice commented on pages/ACTOR_FILE.md
> +  "defaultMemoryMbytes": "{{actorInput.maxParallelRequests}} * 256 + 128",
> Do we want to continue discussion in this long thread PR?

Thanks for this :bow: I haven't fully dived into this yet and I have very few cycles these days. At the same time, I trust you guys that whatever you come up with will make sense. So while my preference would be for all of us to sit properly down later this quarter, you don't have to block on me.

2025-08-07 12:54 UTC, merged